# @name rdpAuth
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

#### Variable Response
@accessToken = {{rdpAuth.response.body.token}}

### Protected route
GET http://localhost:3000/protected
Authorization: Bearer {{accessToken}}

### Home
Get http://localhost:3000/